using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;
using GlDrive.Config;
using GlDrive.Irc;
using Xunit;

namespace GlDrive.Tests;

/// <summary>
/// Known-answer interop tests. The expected values were generated by an independent
/// reference implementation (Python, using the `cryptography` library's Blowfish plus
/// the canonical py-fishcrypt / blog.bjrn.se FiSH + DH1080 algorithms — the same scheme
/// mIRC FiSH 10 / Mircryption / the mIRC blowfish plugin use). If any of these fail,
/// GlDrive's FiSH is NOT byte-compatible with real IRC blowfish clients.
/// </summary>
public class FishInteropVectorTests
{
    // ---- FiSH ECB (Blowfish-ECB + custom FiSH base64) ----
    [Theory]
    [InlineData("blowfish", "Hello World", "+OK tqxf4166nYx.qp/L1/F80.K.")]
    [InlineData("secretkey123", "meet me at 0300 in #ops", "+OK ofGoz0b331p1AgfdB.uNz5F/LmSog0ShcFL.")]
    [InlineData("key1", "test", "+OK NJaFa11bXjN.")]
    public void Ecb_matches_reference_client(string key, string plain, string expectedCipher)
    {
        // Our encrypt must produce the EXACT bytes a reference client produces...
        Assert.Equal(expectedCipher, FishCipher.Encrypt(plain, key, FishMode.ECB));
        // ...and our decrypt must read a reference client's ciphertext.
        Assert.Equal(plain, FishCipher.Decrypt(expectedCipher, key));
    }

    // ---- FiSH CBC (Blowfish-CBC, 8-byte IV prepended, STANDARD base64) ----
    // CBC uses a random IV on encrypt, so we validate by decrypting reference ciphertexts
    // (fixed IV 0x0011223344556677) — the receive path that matters for interop.
    [Theory]
    [InlineData("blowfish", "Hello World", "+OK *ABEiM0RVZneRmWxX3gl3o9a06xRXBRN+")]
    [InlineData("secretkey123", "meet me at 0300 in #ops", "+OK *ABEiM0RVZnccReI8MzuYUX/eWLizxrIfppSnDwh0U6w=")]
    public void Cbc_decrypts_reference_client(string key, string plain, string referenceCipher)
    {
        Assert.Equal(plain, FishCipher.Decrypt(referenceCipher, key));
        // And our own CBC output round-trips (random IV each time).
        Assert.Equal(plain, FishCipher.Decrypt(FishCipher.Encrypt(plain, key, FishMode.CBC), key));
    }

    // ---- DH1080 (fixed private keys → deterministic public keys + derived key) ----
    [Fact]
    public void Dh1080_derivation_matches_reference_client()
    {
        var alicePriv = BigInteger.Parse("0" + new string('a', 100) + "1", NumberStyles.HexNumber);
        var bobPriv   = BigInteger.Parse("0" + new string('b', 100) + "3", NumberStyles.HexNumber);
        const string bobPubHex =
            "3888f860f18d3bc44b475973888f21f6db9d19ae9bd6b8c66996e3e4ef409b4b7d24fe1e585ddbb7b44c3c5d1e685ddaf0b45f8737fb54c6966b41ef800b785857935417344a9a12f3ac72a5267a47f66d758ea43f63106cad2bf6d124ebe0d2adc873512501e61cd2999cdfe021fb50e9937abe0b432670d96fd520f396f474d3fa043c7f0b1b";
        const string expectedDerivedKey = "7xaK6BwyA4J5uApIDn4zU4RbHglwjjM0aZHHIjA1jbc";

        var alice = new Dh1080(alicePriv);

        // Reference Bob's public key, encoded the way FiSH sends it, so ComputeAllKeyVariants
        // exercises the real decode path.
        var bobPubBytes = BigInteger.Parse("0" + bobPubHex, NumberStyles.HexNumber)
            .ToByteArray(isUnsigned: true, isBigEndian: true);
        var bobPubB64 = Convert.ToBase64String(bobPubBytes);

        var derived = alice.ComputeAllKeyVariants(bobPubB64).Standard;
        Assert.Equal(expectedDerivedKey, derived);

        // Sanity: independently confirm Bob (fixed priv) derives the SAME key from Alice's pubkey.
        var bob = new Dh1080(bobPriv);
        Assert.Equal(expectedDerivedKey, bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64()).Standard);
    }

    // A peer that completes a normal DH1080 handshake but derives its Blowfish key with a
    // NON-canonical KDF (here: keeping the base64 '=' padding, a 44-char key, instead of our
    // canonical trimmed 43-char key) must still be readable via alternate-KDF recovery from the
    // stored shared secret — no re-key, no manual key. This is the observed fReeq failure mode.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Alternate_kdf_recovers_peer_with_noncanonical_derivation(FishMode mode)
    {
        var alice = new Dh1080(BigInteger.Pow(3, 411) + 7);
        var bob = new Dh1080(BigInteger.Pow(7, 366) + 11);

        var aliceSecret = alice.ComputeAllKeyVariantsWithSecret(bob.GetPublicKeyBase64()).SecretHex;
        var bobSecret = bob.ComputeAllKeyVariantsWithSecret(alice.GetPublicKeyBase64()).SecretHex;
        Assert.Equal(aliceSecret, bobSecret); // both sides share the same secret

        // The peer encrypts using the non-canonical key = base64(SHA256(shared)) WITH '=' kept.
        var peerKey = Convert.ToBase64String(SHA256.HashData(Convert.FromHexString(bobSecret)));
        const string plain = "clandestine drop at 0400 behind the old mill";
        var cipher = FishCipher.Encrypt(plain, peerKey, mode);

        // Our canonical key is the trimmed 43-char variant — it must NOT equal the peer's key,
        // and decrypting with it yields garbage, not the plaintext.
        var ourCanonical = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard;
        Assert.NotEqual(peerKey, ourCanonical);
        Assert.NotEqual(plain, FishCipher.Decrypt(cipher, ourCanonical));

        // Alternate-KDF recovery from the stored secret finds it.
        var candidates = Dh1080.AlternateKdfCandidates(aliceSecret).ToArray();
        var (decrypted, winIdx, _) = FishCipher.DecryptWithFallback(cipher, candidates);
        Assert.Equal(plain, decrypted);
        Assert.True(winIdx >= 0);
    }

    // Regression for the DH1080 public-key over-strip bug: when a peer's public key's base64
    // encoding ends in 'A' (≈1/64 of keys — low 6 bits of the last byte are zero), the old
    // decoder stripped one 'A' too many, dropped low-order bits, and derived the WRONG key.
    // This silently broke ~1.5% of exchanges per direction. `peerPublic` below is exactly such
    // a public key (its encoding ends in "AA"); the derived key was computed by the reference
    // implementation. With the old decoder this assertion fails.
    [Fact]
    public void Dh1080_decodes_public_key_whose_encoding_ends_in_A()
    {
        const string peerPublic =
            "AAAAAAAA++ECLiPSE+is+proud+to+present+latest+FiSH+release+featuring+even+more+security+for+you+++shout+to+TMG+for+helping+to+generate+this+cool+sophie+germain+prime+number++++/C31AA";
        const string expectedKey = "Rksod4vSi5OdKfaZPRoF4/z9HlMH36/NC3VMI9Gkdco";
        Assert.EndsWith("AA", peerPublic);

        var bob = new Dh1080(BigInteger.Parse("0deadbeef12345678", NumberStyles.HexNumber));
        Assert.Equal(expectedKey, bob.ComputeAllKeyVariants(peerPublic).Standard);
    }

    // Both sides of a real exchange must derive the SAME key — the property every FiSH peer
    // relies on. Deliberately vector-free so it can never go stale when a constant changes;
    // it validates the group arithmetic itself (this is what a wrong modulus breaks).
    [Theory]
    [InlineData("0a1b2c3d4e5f60718293a4b5c6d7e8f9")]
    [InlineData("0deadbeef12345678")]
    [InlineData("016de04c6ce")]
    public void Dh1080_exchange_is_symmetric(string alicePrivHex)
    {
        var alice = new Dh1080(BigInteger.Parse(alicePrivHex, NumberStyles.HexNumber));
        var bob = new Dh1080(BigInteger.Parse("0fedcba9876543210fedcba98765432", NumberStyles.HexNumber));

        var aliceDerived = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard;
        var bobDerived = bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64()).Standard;

        Assert.Equal(aliceDerived, bobDerived);
        Assert.Equal(43, aliceDerived.Length); // base64(SHA-256) with '=' trimmed
    }

    // The DH1080 modulus must be the canonical 1080-bit Sophie Germain SAFE prime.
    // A single wrong hex digit (shipped through v3.10.31 as ...BADBADA3... instead of
    // ...BADFADA3...) yields a COMPOSITE modulus: the exchange still computes, but lands in
    // the wrong group, so no real FiSH client can ever agree on a key — and a composite
    // modulus weakens the discrete log via Pohlig-Hellman. Assert the property directly.
    [Fact]
    public void Dh1080_prime_is_a_1080_bit_safe_prime()
    {
        var p = Dh1080.PrimeForTests;
        Assert.Equal(1080, (int)Math.Floor(BigInteger.Log(p, 2)) + 1);
        Assert.True(IsProbablePrime(p), "DH1080 modulus is not prime");
        Assert.True(IsProbablePrime((p - 1) / 2), "DH1080 modulus is not a safe prime");
    }

    private static bool IsProbablePrime(BigInteger n, int rounds = 20)
    {
        if (n < 2) return false;
        foreach (var sp in new[] { 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37 })
        {
            if (n == sp) return true;
            if (n % sp == 0) return false;
        }

        var d = n - 1;
        var r = 0;
        while (d % 2 == 0) { d /= 2; r++; }

        var rng = new Random(20260721); // fixed seed — deterministic, never flaky
        var buf = new byte[n.ToByteArray().Length];
        for (var i = 0; i < rounds; i++)
        {
            BigInteger a;
            do
            {
                rng.NextBytes(buf);
                buf[^1] &= 0x7F;
                a = new BigInteger(buf);
            } while (a < 2 || a >= n - 1);

            var x = BigInteger.ModPow(a, d, n);
            if (x == 1 || x == n - 1) continue;

            var witnessed = false;
            for (var j = 0; j < r - 1; j++)
            {
                x = BigInteger.ModPow(x, 2, n);
                if (x == n - 1) { witnessed = true; break; }
            }
            if (!witnessed) return false;
        }
        return true;
    }
}

public class FishCipherTests
{
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Encrypt_then_decrypt_round_trips(FishMode mode)
    {
        const string key = "correcthorsebatterystaple";
        const string plain = "the quick brown fox jumps over 13 lazy dogs!";
        var cipher = FishCipher.Encrypt(plain, key, mode);
        Assert.True(FishCipher.IsEncrypted(cipher));
        var back = FishCipher.Decrypt(cipher, key);
        Assert.Equal(plain, back);
    }

    [Fact]
    public void Cbc_and_ecb_produce_distinct_prefixes()
    {
        const string key = "key123key123";
        var ecb = FishCipher.Encrypt("hello", key, FishMode.ECB);
        var cbc = FishCipher.Encrypt("hello", key, FishMode.CBC);
        Assert.StartsWith("+OK ", ecb);
        Assert.StartsWith("+OK *", cbc);
    }

    [Fact]
    public void Decrypt_returns_null_on_garbage()
        => Assert.Null(FishCipher.Decrypt("not encrypted text", "key123key123"));

    // A CORRECT decrypt of non-English text is real plaintext and must score as high quality —
    // otherwise the fallback treats a working key as a failure and (with alt-KDF recovery) could
    // hijack the key. The old quality heuristic only counted ASCII 0x20-0x7E and scored these ~0.
    [Theory]
    [InlineData("Привет мир, как твои дела сегодня")] // Cyrillic
    [InlineData("こんにちは世界、お元気ですか今日は")]      // Japanese
    [InlineData("naive cafe resume facade coeur soeur")] // (ASCII control)
    [InlineData("día lluvioso — piñata, jalapeño ñoño")] // accented Latin + em dash
    public void DecryptWithFallback_accepts_valid_non_ascii_plaintext(string plain)
    {
        const string key = "correcthorsebatterystaple";
        var cipher = FishCipher.Encrypt(plain, key, FishMode.ECB);
        var (decrypted, winIdx, qualities) = FishCipher.DecryptWithFallback(cipher, key, "wrongwrongwrong1");
        Assert.Equal(plain, decrypted);
        Assert.Equal(0, winIdx);
        Assert.True(qualities[0] >= 0.85, $"correct non-ASCII decrypt scored only {qualities[0]:F2}");
    }

    // Regression: an over-length Blowfish key (e.g. the old ~180-byte fishRaw DH1080
    // variant) used to make BouncyCastle throw ArgumentException out of the decrypt
    // path, which unwound the IRC read loop and forced a reconnect. Decrypt must now
    // swallow it and return null; Encrypt must clamp the key and round-trip cleanly.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Over_length_key_never_throws(FishMode mode)
    {
        var hugeKey = new string('A', 180); // 180 bytes — far over Blowfish's 56-byte max

        // A real message encrypted under a *different* short key must not throw when
        // decrypted with the over-length key — it just fails to decrypt.
        var otherCipher = FishCipher.Encrypt("secret", "shortkey123", mode);
        var ex = Record.Exception(() => FishCipher.Decrypt(otherCipher, hugeKey));
        Assert.Null(ex);

        // The over-length key itself must still round-trip (it is clamped to 56 bytes
        // consistently on encrypt and decrypt).
        var cipher = FishCipher.Encrypt("hello world", hugeKey, mode);
        Assert.Equal("hello world", FishCipher.Decrypt(cipher, hugeKey));
    }

    // A peer whose client uses a legacy 8-bit charset (windows-1251 Cyrillic) instead of UTF-8:
    // with the configured fallback charset its messages decode correctly; without it they are
    // garbage (invalid UTF-8), so the UTF-8 wrong-key signal is preserved.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Legacy_charset_peer_decodes_with_fallback(FishMode mode)
    {
        System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        var cp1251 = System.Text.Encoding.GetEncoding("windows-1251");
        const string key = "correcthorsebatterystaple";
        const string plain = "Привет мир, как твои дела сегодня друг";

        // Peer encrypts the CP1251 bytes of the message (not UTF-8).
        var cipher = FishCipher.Encrypt(plain, key, mode, cp1251);

        // With the fallback charset we recover the Cyrillic text...
        var (withCharset, wIdx, wQ) = FishCipher.DecryptWithFallback(cipher, cp1251, key, "wrongwrong123456");
        Assert.Equal(plain, withCharset);
        Assert.Equal(0, wIdx);
        Assert.True(wQ[0] >= 0.85);

        // ...but without it, UTF-8 decoding of CP1251 bytes yields U+FFFD garbage (not the plaintext).
        Assert.NotEqual(plain, FishCipher.Decrypt(cipher, key));
    }

    // Windows-1252 text using common typographic glyphs that live at 0x80-0x9F (apostrophe 0x92,
    // em-dash 0x97, curly quotes 0x93/0x94, ellipsis 0x85) must still decode — the gate is
    // charset-aware (checks decoded chars, not raw C1 bytes), so real punctuation is accepted.
    [Fact]
    public void Legacy_charset_decodes_windows1252_smart_punctuation()
    {
        System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        var cp1252 = System.Text.Encoding.GetEncoding("windows-1252");
        const string key = "correcthorsebatterystaple";
        const string plain = "It’s over here — “the café” closes at 8…";
        var cipher = FishCipher.Encrypt(plain, key, FishMode.ECB, cp1252);
        var (text, idx, _) = FishCipher.DecryptWithFallback(cipher, cp1252, key, "wrongwrong123456");
        Assert.Equal(plain, text);
        Assert.Equal(0, idx);
    }

    // A sub-16-byte legacy decrypt is NOT trusted as legacy text (too short to distinguish from a
    // random wrong-key block), so the fallback is refused even with the charset set — this is the
    // guard that stops a wrong key from "decoding" short random bytes into bogus glyphs.
    [Fact]
    public void Legacy_charset_refuses_too_short_messages()
    {
        System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        var cp1251 = System.Text.Encoding.GetEncoding("windows-1251");
        const string key = "correcthorsebatterystaple";
        const string shortPlain = "Привет"; // 6 CP1251 bytes — below the 16-byte legacy gate
        var cipher = FishCipher.Encrypt(shortPlain, key, FishMode.ECB, cp1251);
        Assert.NotEqual(shortPlain, FishCipher.Decrypt(cipher, key, cp1251));
    }

    [Fact]
    public void DecryptWithFallback_never_throws_on_bad_keys()
    {
        // Feed a mix of empty, over-length, and wrong keys — must return without throwing.
        var cipher = FishCipher.Encrypt("hi", "realkey123", FishMode.ECB);
        var ex = Record.Exception(() =>
            FishCipher.DecryptWithFallback(cipher, "", new string('Z', 200), "wrongkey"));
        Assert.Null(ex);
    }
}

public class Dh1080Tests
{
    [Fact]
    public void Both_parties_derive_the_same_key_variants()
    {
        // Deterministic fixed private keys (not random) so this can never flake on the
        // rare, ecosystem-wide DH1080 wire-format edge case. Both parties MUST derive
        // byte-identical key variants from every exchange — a regression in the pubkey
        // encode/decode round-trip (see Dh1080_decodes_public_key_whose_encoding_ends_in_A)
        // would make many of these disagree.
        for (var seed = 1; seed <= 40; seed++)
        {
            var alice = new Dh1080(BigInteger.Pow(3, 400 + seed) + seed);
            var bob   = new Dh1080(BigInteger.Pow(7, 350 + seed) + seed * 13);
            var ak = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64());
            var bk = bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64());
            Assert.False(string.IsNullOrEmpty(ak.Standard));
            Assert.Equal(ak.Standard, bk.Standard);
            Assert.Equal(ak.Fish, bk.Fish);
        }
    }

    [Fact]
    public void Public_key_is_nonempty()
        => Assert.False(string.IsNullOrEmpty(new Dh1080().GetPublicKeyBase64()));

    // Auto-recovery policy: a stale/corrupt DH1080 key re-negotiates itself after a few
    // consecutive decrypt failures, but is rate-limited (cooldown) AND capped (max attempts per
    // episode) so a peer a fresh exchange can never repair can't drive an endless /keyx stream.
    [Theory]
    [InlineData(1, 999, 0, false)] // first failure — below threshold
    [InlineData(2, 999, 0, false)] // second failure — still below threshold
    [InlineData(3, 999, 0, true)]  // third consecutive failure, cooldown elapsed, budget left — re-key
    [InlineData(5, 999, 1, true)]  // past threshold, cooldown elapsed, 1 prior attempt — re-key
    [InlineData(3, 1, 0, false)]   // threshold reached but within cooldown — suppressed
    [InlineData(9, 999, 3, false)] // budget exhausted (3 prior attempts) — give up, no more /keyx
    [InlineData(9, 999, 2, true)]  // exactly at the last allowed attempt — still re-key
    public void Auto_rekey_policy_respects_threshold_cooldown_and_cap(int streak, int minutesSinceLast, int priorAttempts, bool expected)
        => Assert.Equal(expected, IrcService.ShouldAutoRekey(streak, TimeSpan.FromMinutes(minutesSinceLast), priorAttempts));

    // The canonical DH1080 Blowfish key (mIRC FiSH 10, weechat fish.py, HexChat, KVIrc,
    // py-fishcrypt) is standard-RFC4648-base64(SHA256(shared_secret)) with '=' padding
    // stripped. Our Standard variant must equal exactly that, and must be a valid
    // Blowfish key length (43 bytes, within 4..56).
    [Fact]
    public void Standard_variant_matches_canonical_derivation_and_is_valid_length()
    {
        var alice = new Dh1080();
        var bob = new Dh1080();
        var std = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard;
        Assert.Equal(43, std.Length);                  // 32-byte SHA-256 digest -> 43 base64 chars
        Assert.InRange(Encoding.Latin1.GetBytes(std).Length, 4, 56); // usable Blowfish key
    }

    // End-to-end proof that DH1080 private-message encryption actually works: two parties
    // exchange public keys, derive the key, then one encrypts and the other decrypts via
    // the same fallback path the live IRC handlers use. This is the behaviour the user
    // reported as "doesn't work at all" — it was masked by the fishRaw-variant crash.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Dh1080_derived_key_round_trips_a_private_message(FishMode mode)
    {
        var alice = new Dh1080();
        var bob = new Dh1080();
        var aliceKeys = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64());
        var bobKeys = bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64());

        const string plain = "meet me in #ops - the eagle lands at 0300";

        // Alice encrypts with her derived (canonical Standard) key.
        var cipher = FishCipher.Encrypt(plain, aliceKeys.Standard, mode);

        // Bob decrypts via the try-all-variants fallback (Standard, Fish).
        var (decrypted, winIdx, _) =
            FishCipher.DecryptWithFallback(cipher, bobKeys.Standard, bobKeys.Fish);

        Assert.Equal(plain, decrypted);
        Assert.Equal(0, winIdx); // Standard variant wins — it is the canonical key
    }
}
