using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;
using GlDrive.Config;
using GlDrive.Irc;
using Xunit;

namespace GlDrive.Tests;

/// <summary>
/// Known-answer interop tests. The expected values were generated by an independent
/// reference implementation (Python, using the `cryptography` library's Blowfish plus
/// the canonical py-fishcrypt / blog.bjrn.se FiSH + DH1080 algorithms — the same scheme
/// mIRC FiSH 10 / Mircryption / the mIRC blowfish plugin use). If any of these fail,
/// GlDrive's FiSH is NOT byte-compatible with real IRC blowfish clients.
/// </summary>
public class FishInteropVectorTests
{
    // ---- FiSH ECB (Blowfish-ECB + custom FiSH base64) ----
    [Theory]
    [InlineData("blowfish", "Hello World", "+OK tqxf4166nYx.qp/L1/F80.K.")]
    [InlineData("secretkey123", "meet me at 0300 in #ops", "+OK ofGoz0b331p1AgfdB.uNz5F/LmSog0ShcFL.")]
    [InlineData("key1", "test", "+OK NJaFa11bXjN.")]
    public void Ecb_matches_reference_client(string key, string plain, string expectedCipher)
    {
        // Our encrypt must produce the EXACT bytes a reference client produces...
        Assert.Equal(expectedCipher, FishCipher.Encrypt(plain, key, FishMode.ECB));
        // ...and our decrypt must read a reference client's ciphertext.
        Assert.Equal(plain, FishCipher.Decrypt(expectedCipher, key));
    }

    // ---- FiSH CBC (Blowfish-CBC, 8-byte IV prepended, STANDARD base64) ----
    // CBC uses a random IV on encrypt, so we validate by decrypting reference ciphertexts
    // (fixed IV 0x0011223344556677) — the receive path that matters for interop.
    [Theory]
    [InlineData("blowfish", "Hello World", "+OK *ABEiM0RVZneRmWxX3gl3o9a06xRXBRN+")]
    [InlineData("secretkey123", "meet me at 0300 in #ops", "+OK *ABEiM0RVZnccReI8MzuYUX/eWLizxrIfppSnDwh0U6w=")]
    public void Cbc_decrypts_reference_client(string key, string plain, string referenceCipher)
    {
        Assert.Equal(plain, FishCipher.Decrypt(referenceCipher, key));
        // And our own CBC output round-trips (random IV each time).
        Assert.Equal(plain, FishCipher.Decrypt(FishCipher.Encrypt(plain, key, FishMode.CBC), key));
    }

    // ---- DH1080 (fixed private keys → deterministic public keys + derived key) ----
    [Fact]
    public void Dh1080_derivation_matches_reference_client()
    {
        var alicePriv = BigInteger.Parse("0" + new string('a', 100) + "1", NumberStyles.HexNumber);
        var bobPriv   = BigInteger.Parse("0" + new string('b', 100) + "3", NumberStyles.HexNumber);
        const string bobPubHex =
            "e6a585ff851073ff3ce3d5eade5539bd114ae55684dbcd3f53d9f95de137c249d3dbd1ca203dbeb6b7f2997109479340de3fc0a968527035ffc104d767955190bf54de752cb3d1d66758917f2fc6bd5da8ec54faf0305f554b49b086edc5c911620e278da9b55c96c7bfa22a2dd249c3dea9a3d86a3c2239163676b7e040bc0a03a11644f5063f";
        const string expectedDerivedKey = "9VDM96YLmLbQ+mVFAU+W74ulyllppD77zg/CEdlEya8";

        var alice = new Dh1080(alicePriv);

        // Reference Bob's public key, encoded the way FiSH sends it, so ComputeAllKeyVariants
        // exercises the real decode path.
        var bobPubBytes = BigInteger.Parse("0" + bobPubHex, NumberStyles.HexNumber)
            .ToByteArray(isUnsigned: true, isBigEndian: true);
        var bobPubB64 = Convert.ToBase64String(bobPubBytes);

        var derived = alice.ComputeAllKeyVariants(bobPubB64).Standard;
        Assert.Equal(expectedDerivedKey, derived);

        // Sanity: independently confirm Bob (fixed priv) derives the SAME key from Alice's pubkey.
        var bob = new Dh1080(bobPriv);
        Assert.Equal(expectedDerivedKey, bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64()).Standard);
    }

    // A peer that completes a normal DH1080 handshake but derives its Blowfish key with a
    // NON-canonical KDF (here: keeping the base64 '=' padding, a 44-char key, instead of our
    // canonical trimmed 43-char key) must still be readable via alternate-KDF recovery from the
    // stored shared secret — no re-key, no manual key. This is the observed fReeq failure mode.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Alternate_kdf_recovers_peer_with_noncanonical_derivation(FishMode mode)
    {
        var alice = new Dh1080(BigInteger.Pow(3, 411) + 7);
        var bob = new Dh1080(BigInteger.Pow(7, 366) + 11);

        var aliceSecret = alice.ComputeAllKeyVariantsWithSecret(bob.GetPublicKeyBase64()).SecretHex;
        var bobSecret = bob.ComputeAllKeyVariantsWithSecret(alice.GetPublicKeyBase64()).SecretHex;
        Assert.Equal(aliceSecret, bobSecret); // both sides share the same secret

        // The peer encrypts using the non-canonical key = base64(SHA256(shared)) WITH '=' kept.
        var peerKey = Convert.ToBase64String(SHA256.HashData(Convert.FromHexString(bobSecret)));
        const string plain = "clandestine drop at 0400 behind the old mill";
        var cipher = FishCipher.Encrypt(plain, peerKey, mode);

        // Our canonical key is the trimmed 43-char variant — it must NOT equal the peer's key,
        // and decrypting with it yields garbage, not the plaintext.
        var ourCanonical = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard;
        Assert.NotEqual(peerKey, ourCanonical);
        Assert.NotEqual(plain, FishCipher.Decrypt(cipher, ourCanonical));

        // Alternate-KDF recovery from the stored secret finds it.
        var candidates = Dh1080.AlternateKdfCandidates(aliceSecret).ToArray();
        var (decrypted, winIdx, _) = FishCipher.DecryptWithFallback(cipher, candidates);
        Assert.Equal(plain, decrypted);
        Assert.True(winIdx >= 0);
    }

    // Regression for the DH1080 public-key over-strip bug: when a peer's public key's base64
    // encoding ends in 'A' (≈1/64 of keys — low 6 bits of the last byte are zero), the old
    // decoder stripped one 'A' too many, dropped low-order bits, and derived the WRONG key.
    // This silently broke ~1.5% of exchanges per direction. `aliceEnc` below is exactly such
    // a public key (its encoding ends in "AA"); the derived key was computed by the reference
    // implementation. With the old decoder this assertion fails.
    [Fact]
    public void Dh1080_decodes_public_key_whose_encoding_ends_in_A()
    {
        const string aliceEnc =
            "kn32DvrGzngFhz9BwqLDqZy4EWrsVXmmzI5bZAXxvJYuJaRex/uKO1BtnIJcy6yVaTIQqVOQon4hJgh54StsFDOADQ/KxLYjqmulqaE61WcX8djhQDwuAaHfAsoVKstrMDmCiPUAyoqFWVZaIjIldFOId1yqSqGkvpLgJJcGIMFugKCp90MAA";
        const string expectedKey = "12Dg95VHInVz1ZBVkullF6rxnBy2y7h8xP+150gwnnM";
        Assert.EndsWith("AA", aliceEnc);

        var bob = new Dh1080(BigInteger.Parse("0deadbeef12345678", NumberStyles.HexNumber));
        Assert.Equal(expectedKey, bob.ComputeAllKeyVariants(aliceEnc).Standard);

        // Symmetric: Alice (the fixed private key that produced aliceEnc) derives the same
        // key from Bob's public key — proving the exchange round-trips end to end.
        var alice = new Dh1080(BigInteger.Parse("016de04c6ce", NumberStyles.HexNumber));
        Assert.Equal(expectedKey, alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard);
    }
}

public class FishCipherTests
{
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Encrypt_then_decrypt_round_trips(FishMode mode)
    {
        const string key = "correcthorsebatterystaple";
        const string plain = "the quick brown fox jumps over 13 lazy dogs!";
        var cipher = FishCipher.Encrypt(plain, key, mode);
        Assert.True(FishCipher.IsEncrypted(cipher));
        var back = FishCipher.Decrypt(cipher, key);
        Assert.Equal(plain, back);
    }

    [Fact]
    public void Cbc_and_ecb_produce_distinct_prefixes()
    {
        const string key = "key123key123";
        var ecb = FishCipher.Encrypt("hello", key, FishMode.ECB);
        var cbc = FishCipher.Encrypt("hello", key, FishMode.CBC);
        Assert.StartsWith("+OK ", ecb);
        Assert.StartsWith("+OK *", cbc);
    }

    [Fact]
    public void Decrypt_returns_null_on_garbage()
        => Assert.Null(FishCipher.Decrypt("not encrypted text", "key123key123"));

    // A CORRECT decrypt of non-English text is real plaintext and must score as high quality —
    // otherwise the fallback treats a working key as a failure and (with alt-KDF recovery) could
    // hijack the key. The old quality heuristic only counted ASCII 0x20-0x7E and scored these ~0.
    [Theory]
    [InlineData("Привет мир, как твои дела сегодня")] // Cyrillic
    [InlineData("こんにちは世界、お元気ですか今日は")]      // Japanese
    [InlineData("naive cafe resume facade coeur soeur")] // (ASCII control)
    [InlineData("día lluvioso — piñata, jalapeño ñoño")] // accented Latin + em dash
    public void DecryptWithFallback_accepts_valid_non_ascii_plaintext(string plain)
    {
        const string key = "correcthorsebatterystaple";
        var cipher = FishCipher.Encrypt(plain, key, FishMode.ECB);
        var (decrypted, winIdx, qualities) = FishCipher.DecryptWithFallback(cipher, key, "wrongwrongwrong1");
        Assert.Equal(plain, decrypted);
        Assert.Equal(0, winIdx);
        Assert.True(qualities[0] >= 0.85, $"correct non-ASCII decrypt scored only {qualities[0]:F2}");
    }

    // Regression: an over-length Blowfish key (e.g. the old ~180-byte fishRaw DH1080
    // variant) used to make BouncyCastle throw ArgumentException out of the decrypt
    // path, which unwound the IRC read loop and forced a reconnect. Decrypt must now
    // swallow it and return null; Encrypt must clamp the key and round-trip cleanly.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Over_length_key_never_throws(FishMode mode)
    {
        var hugeKey = new string('A', 180); // 180 bytes — far over Blowfish's 56-byte max

        // A real message encrypted under a *different* short key must not throw when
        // decrypted with the over-length key — it just fails to decrypt.
        var otherCipher = FishCipher.Encrypt("secret", "shortkey123", mode);
        var ex = Record.Exception(() => FishCipher.Decrypt(otherCipher, hugeKey));
        Assert.Null(ex);

        // The over-length key itself must still round-trip (it is clamped to 56 bytes
        // consistently on encrypt and decrypt).
        var cipher = FishCipher.Encrypt("hello world", hugeKey, mode);
        Assert.Equal("hello world", FishCipher.Decrypt(cipher, hugeKey));
    }

    [Fact]
    public void DecryptWithFallback_never_throws_on_bad_keys()
    {
        // Feed a mix of empty, over-length, and wrong keys — must return without throwing.
        var cipher = FishCipher.Encrypt("hi", "realkey123", FishMode.ECB);
        var ex = Record.Exception(() =>
            FishCipher.DecryptWithFallback(cipher, "", new string('Z', 200), "wrongkey"));
        Assert.Null(ex);
    }
}

public class Dh1080Tests
{
    [Fact]
    public void Both_parties_derive_the_same_key_variants()
    {
        // Deterministic fixed private keys (not random) so this can never flake on the
        // rare, ecosystem-wide DH1080 wire-format edge case. Both parties MUST derive
        // byte-identical key variants from every exchange — a regression in the pubkey
        // encode/decode round-trip (see Dh1080_decodes_public_key_whose_encoding_ends_in_A)
        // would make many of these disagree.
        for (var seed = 1; seed <= 40; seed++)
        {
            var alice = new Dh1080(BigInteger.Pow(3, 400 + seed) + seed);
            var bob   = new Dh1080(BigInteger.Pow(7, 350 + seed) + seed * 13);
            var ak = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64());
            var bk = bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64());
            Assert.False(string.IsNullOrEmpty(ak.Standard));
            Assert.Equal(ak.Standard, bk.Standard);
            Assert.Equal(ak.Fish, bk.Fish);
        }
    }

    [Fact]
    public void Public_key_is_nonempty()
        => Assert.False(string.IsNullOrEmpty(new Dh1080().GetPublicKeyBase64()));

    // Auto-recovery policy: a stale/corrupt DH1080 key re-negotiates itself after a few
    // consecutive decrypt failures, but is rate-limited (cooldown) AND capped (max attempts per
    // episode) so a peer a fresh exchange can never repair can't drive an endless /keyx stream.
    [Theory]
    [InlineData(1, 999, 0, false)] // first failure — below threshold
    [InlineData(2, 999, 0, false)] // second failure — still below threshold
    [InlineData(3, 999, 0, true)]  // third consecutive failure, cooldown elapsed, budget left — re-key
    [InlineData(5, 999, 1, true)]  // past threshold, cooldown elapsed, 1 prior attempt — re-key
    [InlineData(3, 1, 0, false)]   // threshold reached but within cooldown — suppressed
    [InlineData(9, 999, 3, false)] // budget exhausted (3 prior attempts) — give up, no more /keyx
    [InlineData(9, 999, 2, true)]  // exactly at the last allowed attempt — still re-key
    public void Auto_rekey_policy_respects_threshold_cooldown_and_cap(int streak, int minutesSinceLast, int priorAttempts, bool expected)
        => Assert.Equal(expected, IrcService.ShouldAutoRekey(streak, TimeSpan.FromMinutes(minutesSinceLast), priorAttempts));

    // The canonical DH1080 Blowfish key (mIRC FiSH 10, weechat fish.py, HexChat, KVIrc,
    // py-fishcrypt) is standard-RFC4648-base64(SHA256(shared_secret)) with '=' padding
    // stripped. Our Standard variant must equal exactly that, and must be a valid
    // Blowfish key length (43 bytes, within 4..56).
    [Fact]
    public void Standard_variant_matches_canonical_derivation_and_is_valid_length()
    {
        var alice = new Dh1080();
        var bob = new Dh1080();
        var std = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64()).Standard;
        Assert.Equal(43, std.Length);                  // 32-byte SHA-256 digest -> 43 base64 chars
        Assert.InRange(Encoding.Latin1.GetBytes(std).Length, 4, 56); // usable Blowfish key
    }

    // End-to-end proof that DH1080 private-message encryption actually works: two parties
    // exchange public keys, derive the key, then one encrypts and the other decrypts via
    // the same fallback path the live IRC handlers use. This is the behaviour the user
    // reported as "doesn't work at all" — it was masked by the fishRaw-variant crash.
    [Theory]
    [InlineData(FishMode.ECB)]
    [InlineData(FishMode.CBC)]
    public void Dh1080_derived_key_round_trips_a_private_message(FishMode mode)
    {
        var alice = new Dh1080();
        var bob = new Dh1080();
        var aliceKeys = alice.ComputeAllKeyVariants(bob.GetPublicKeyBase64());
        var bobKeys = bob.ComputeAllKeyVariants(alice.GetPublicKeyBase64());

        const string plain = "meet me in #ops - the eagle lands at 0300";

        // Alice encrypts with her derived (canonical Standard) key.
        var cipher = FishCipher.Encrypt(plain, aliceKeys.Standard, mode);

        // Bob decrypts via the try-all-variants fallback (Standard, Fish).
        var (decrypted, winIdx, _) =
            FishCipher.DecryptWithFallback(cipher, bobKeys.Standard, bobKeys.Fish);

        Assert.Equal(plain, decrypted);
        Assert.Equal(0, winIdx); // Standard variant wins — it is the canonical key
    }
}
